name: TLC JPF Tests
# These test take a long time to run (> 6 hours on GitHub ci).
# It's run whenever the tested classes are updated.

on:
  push:
    paths:
      - 'tlatools/org.lamport.tlatools/src/tlc2/tool/fp/OffHeapDiskFPSet.java'
      - 'tlatools/org.lamport.tlatools/test-verify/tlc2/tool/fp/OffHeapDiskFPSetJPFTest.java'
      - 'tlatools/org.lamport.tlatools/src/tlc2/tool/queue/StateQueue.java'
      - 'tlatools/org.lamport.tlatools/test-verify/tlc2/tool/queue/StateQueueJPFTest.java'
  pull_request:
    paths:
      - 'tlatools/org.lamport.tlatools/src/tlc2/tool/fp/OffHeapDiskFPSet.java'
      - 'tlatools/org.lamport.tlatools/test-verify/tlc2/tool/fp/OffHeapDiskFPSetJPFTest.java'
      - 'tlatools/org.lamport.tlatools/src/tlc2/tool/queue/StateQueue.java'
      - 'tlatools/org.lamport.tlatools/test-verify/tlc2/tool/queue/StateQueueJPFTest.java'

jobs:
  run-tlc-test-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history.
          # jgit task nested in customBuild.xml fails without history.
          fetch-depth: '0'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 22

      - name: Run TLC test verify
        run: ant -f tlatools/org.lamport.tlatools/customBuild.xml -Dtest.halt=true compile compile-test test-verify info
